//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadCCDKPI", ReplyAction="http://tempuri.org/IService/UploadCCDKPIResponse")]
        bool UploadCCDKPI(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadCCDKPI", ReplyAction="http://tempuri.org/IService/UploadCCDKPIResponse")]
        System.Threading.Tasks.Task<bool> UploadCCDKPIAsync(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadCCDAlramInfo", ReplyAction="http://tempuri.org/IService/UploadCCDAlramInfoResponse")]
        bool UploadCCDAlramInfo(string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UploadCCDAlramInfo", ReplyAction="http://tempuri.org/IService/UploadCCDAlramInfoResponse")]
        System.Threading.Tasks.Task<bool> UploadCCDAlramInfoAsync(string parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ServerTest.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServerTest.ServiceReference1.IService>, ServerTest.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UploadCCDKPI(string parameters) {
            return base.Channel.UploadCCDKPI(parameters);
        }
        
        public System.Threading.Tasks.Task<bool> UploadCCDKPIAsync(string parameters) {
            return base.Channel.UploadCCDKPIAsync(parameters);
        }
        
        public bool UploadCCDAlramInfo(string parameters) {
            return base.Channel.UploadCCDAlramInfo(parameters);
        }
        
        public System.Threading.Tasks.Task<bool> UploadCCDAlramInfoAsync(string parameters) {
            return base.Channel.UploadCCDAlramInfoAsync(parameters);
        }
    }
}
